### PR TITLE
Deintegrate user script phases

### PR DESCRIPTION
**Pull request by dnkoutso**
This ensures the deintegrator cleans up the user script phases setup in the podfile for any target.

### CODE REVIEW

**Comment by dnkoutso** [comment]
Hm how long has this been since this project has been built? Getting a build failure

**Comment by segiddins** [comment]
last built a year ago

**Comment by dnkoutso** [comment]
Hm

```
/Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:17:in `require': cannot load such file -- stringio (LoadError)
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:17:in `<top (required)>'
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems.rb:1334:in `require'
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems.rb:1334:in `<module:Gem>'
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems.rb:116:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'
$ gem --version
/Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:17:in `require': cannot load such file -- stringio (LoadError)
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:17:in `<top (required)>'
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems.rb:1334:in `require'
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems.rb:1334:in `<module:Gem>'
	from /Users/travis/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems.rb:116:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
```

**Comment by dnkoutso** [comment]
Build queued up forever, but still fails

**Comment by dnkoutso** [comment]
argh @DanToml any pointers on how to handle the build failure? I don't quite get it :|

**Comment by segiddins** [comment]
That just looks like travis' ruby is broken. Let's do what we did for CocoaPods/CocoaPods and just test the latest 2.0.0, and let's update to `trusty` while we're at it

**Comment by dnkoutso** [comment]
Updated. 3 separate commits.

**Comment by segiddins** [comment]
👍 if it passes

**Comment by dnkoutso** [comment]
Bleh same problem

**Comment by segiddins** [comment]
Silly me, we can also remove the `os: osx` bit now because CocoaPods no longer requires macOS

**Comment by dnkoutso** [comment]
Done.

**Comment by dnkoutso** [comment]
OMG! :D GREEN!

**Pull request merged**
