### PR TITLE
Fixed cocoa pod gem install instruction

### PR DESCRIPTION
**Pull request by Brown-amazingness**
you need to use sudo to install the cocoapods deintegrate gem

### CODE REVIEW

**Comment by segiddins** [comment]
You only need sudo if you're using the default ruby installation and haven't changed your gem home. I believe elsewhere we write it `[sudo]`, maybe we ought to do the same here?

**Comment by orta** [comment]
@Brown-amazingness cool, can you make this `[sudo]` we want people to know that it is optional please :dancers:

**Comment by segiddins** [comment]
@Brown-amazingness ping?

**Comment by segiddins** [comment]
Thanks!

**Pull request merged**
